# Generated by Django 2.2.4 on 2019-10-22 06:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='like_users',
            field=models.ManyToManyField(related_name='likes_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
